# Generated by Django 4.2.23 on 2025-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "titulo",
                    models.CharField(help_text="Título descriptivo de la tarea", max_length=200, verbose_name="Título"),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[("baja", "Baja"), ("media", "Media"), ("alta", "Alta"), ("urgente", "Urgente")],
                        default="media",
                        help_text="Nivel de prioridad de la tarea",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En Progreso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        help_text="Estado actual de la tarea",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_limite",
                    models.DateTimeField(help_text="Fecha y hora límite para completar la tarea", verbose_name="Fecha Límite"),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada de la tarea (opcional)",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación")),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualización")),
                (
                    "completada_en",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando se completó la tarea",
                        null=True,
                        verbose_name="Completada en",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
