name: Django CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Django tests
      run: |
        python manage.py test app --verbosity=2
      env:
        SECRET_KEY: django-insecure-test-key-for-ci-only
        DEBUG: True
        ALLOWED_HOSTS: localhost,127.0.0.1
    
    - name: Check code quality
      run: |
        flake8 app/ --max-line-length=127 --exclude=migrations || true
        black --check app/ --exclude=migrations || true
